In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
diff = pd.read_csv("difference.csv")
FB = pd.read_csv("final_FBREF_Scraping.csv")

In [3]:
FB.drop('Position', axis = 1, inplace = True)
FB.drop('Unnamed: 0', axis = 1, inplace = True)
diff.drop('Unnamed: 0', axis = 1, inplace = True)
FB = FB.rename(columns = {'Player': 'Players'})

In [5]:
FB.shape

(3310, 47)

In [6]:
diff.shape

(3370, 6)

# Replacing Special Characters

In [7]:
from unidecode import unidecode

In [8]:
FB['Players'] = FB['Players'].apply(unidecode)
diff['Players'] = diff['Players'].apply(unidecode)

In [10]:
FB

,Players,Age,Matches Played,Start,Minutes,Goals,Assists,Penalties Made,Yellow Cards,Red Cards,...,Goal Defense,Tackles,Tackles Won,Challenges,Successful Challenge %,Blocks,Interceptions,Tackles + Interceptions,Clearances,Errors
0,Ederson,28,35,35,"3,150",0.0,1.0,0.0,3.0,0.0,...,0.0,3.0,1,1.0,50.0,0.0,1,4.0,10.0,2.0
1,Rodri,26,36,34,"2,911",2.0,6.0,0.0,5.0,0.0,...,0.0,67.0,41,26.0,50.0,40.0,33,100.0,43.0,1.0
2,Haaland Erling,22,35,33,"2,769",36.0,8.0,7.0,5.0,0.0,...,0.0,3.0,2,1.0,20.0,12.0,3,6.0,14.0,0.0
3,De Bruyne Kevin,31,32,28,"2,417",7.0,16.0,0.0,1.0,0.0,...,0.0,28.0,12,14.0,35.9,27.0,9,37.0,10.0,0.0
4,Gundogan Ilkay,31,31,27,"2,353",8.0,4.0,0.0,0.0,0.0,...,0.0,30.0,18,12.0,36.4,18.0,20,50.0,13.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3305,Valente Luciano,18,20,9,874,0.0,0.0,0.0,4.0,0.0,...,0.0,17.0,10,6.0,37.5,15.0,3,20.0,8.0,0.0
3306,Irandust Daleho,24,17,9,747,0.0,4.0,0.0,1.0,0.0,...,0.0,19.0,11,9.0,56.3,8.0,4,23.0,2.0,0.0
3307,Leeuwenburgh Peter,28,8,8,673,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0,0.0,NaN,0.0,1,1.0,2.0,0.0
3308,Antman Oliver,20,11,8,670,2.0,1.0,0.0,0.0,0.0,...,0.0,9.0,7,5.0,41.7,9.0,2,11.0,5.0,0.0
3309,Ngonge Cyril,22,12,8,655,3.0,2.0,0.0,0.0,0.0,...,0.0,10.0,7,5.0,62.5,9.0,8,18.0,7.0,0.0

In [11]:
diff

,Players,Club,Position,Age,Nationality,Values
0,Bruno Fernandes,Manchester United,midfield,28,Portugal,74900000.0
1,Randal Kolo Muani,Eintracht Frankfurt,Attack,24,France,64000000.0
2,Antony,Manchester United,Attack,23,Brazil,59700000.0
3,Bukayo Saka,Arsenal FC,Attack,21,England,55000000.0
4,Victor Osimhen,SSC Napoli,Attack,24,Nigeria,55000000.0
...,...,...,...,...,...,...
3365,Andre Silva,Vitória Guimarães SC,Attack,26,Brazil,-30000000.0
3366,Paul Pogba,Juventus FC,midfield,30,France,-33000000.0
3367,Antony,FC Arouca,Attack,21,Brazil,-34400000.0
3368,Sadio Mane,Bayern Munich,Attack,31,Senegal,-45000000.0
3369,Marquinhos,Arsenal FC,Attack,20,Brazil,-58000000.0

# Changing Name Order of FBREF Dataset

In [13]:
def process_name(name):
    name_parts = name.split(' ')
    if len(name_parts) >= 3:
        space_index = name.find(' ')
        name = name[:space_index] + '$' + name[space_index+1:]
    return name

# Apply the function to the 'Player' column
FB['Players'] = FB['Players'].apply(process_name)

# Print the updated DataFrame
FB

,Players,Age,Matches Played,Start,Minutes,Goals,Assists,Penalties Made,Yellow Cards,Red Cards,...,Goal Defense,Tackles,Tackles Won,Challenges,Successful Challenge %,Blocks,Interceptions,Tackles + Interceptions,Clearances,Errors
0,Ederson,28,35,35,"3,150",0.0,1.0,0.0,3.0,0.0,...,0.0,3.0,1,1.0,50.0,0.0,1,4.0,10.0,2.0
1,Rodri,26,36,34,"2,911",2.0,6.0,0.0,5.0,0.0,...,0.0,67.0,41,26.0,50.0,40.0,33,100.0,43.0,1.0
2,Haaland Erling,22,35,33,"2,769",36.0,8.0,7.0,5.0,0.0,...,0.0,3.0,2,1.0,20.0,12.0,3,6.0,14.0,0.0
3,De$Bruyne Kevin,31,32,28,"2,417",7.0,16.0,0.0,1.0,0.0,...,0.0,28.0,12,14.0,35.9,27.0,9,37.0,10.0,0.0
4,Gundogan Ilkay,31,31,27,"2,353",8.0,4.0,0.0,0.0,0.0,...,0.0,30.0,18,12.0,36.4,18.0,20,50.0,13.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3305,Valente Luciano,18,20,9,874,0.0,0.0,0.0,4.0,0.0,...,0.0,17.0,10,6.0,37.5,15.0,3,20.0,8.0,0.0
3306,Irandust Daleho,24,17,9,747,0.0,4.0,0.0,1.0,0.0,...,0.0,19.0,11,9.0,56.3,8.0,4,23.0,2.0,0.0
3307,Leeuwenburgh Peter,28,8,8,673,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0,0.0,NaN,0.0,1,1.0,2.0,0.0
3308,Antman Oliver,20,11,8,670,2.0,1.0,0.0,0.0,0.0,...,0.0,9.0,7,5.0,41.7,9.0,2,11.0,5.0,0.0
3309,Ngonge Cyril,22,12,8,655,3.0,2.0,0.0,0.0,0.0,...,0.0,10.0,7,5.0,62.5,9.0,8,18.0,7.0,0.0

In [16]:
FB['Players'] = FB['Players'].apply(lambda x: ' '.join(x.split()[::-1]))
FB.head(5)

,Players,Age,Matches Played,Start,Minutes,Goals,Assists,Penalties Made,Yellow Cards,Red Cards,...,Goal Defense,Tackles,Tackles Won,Challenges,Successful Challenge %,Blocks,Interceptions,Tackles + Interceptions,Clearances,Errors
0,Ederson,28,35,35,"3,150",0.0,1.0,0.0,3.0,0.0,...,0.0,3.0,1,1.0,50.0,0.0,1,4.0,10.0,2.0
1,Rodri,26,36,34,"2,911",2.0,6.0,0.0,5.0,0.0,...,0.0,67.0,41,26.0,50.0,40.0,33,100.0,43.0,1.0
2,Erling Haaland,22,35,33,"2,769",36.0,8.0,7.0,5.0,0.0,...,0.0,3.0,2,1.0,20.0,12.0,3,6.0,14.0,0.0
3,Kevin De$Bruyne,31,32,28,"2,417",7.0,16.0,0.0,1.0,0.0,...,0.0,28.0,12,14.0,35.9,27.0,9,37.0,10.0,0.0
4,Ilkay Gundogan,31,31,27,"2,353",8.0,4.0,0.0,0.0,0.0,...,0.0,30.0,18,12.0,36.4,18.0,20,50.0,13.0,0.0

In [17]:
def remove_dollar_sign(name):
    return name.replace('$', ' ')

# Apply the function to the 'Player' column where names contain a dollar sign
FB.loc[FB['Players'].str.contains('\$'), 'Players'] = FB.loc[FB['Players'].str.contains('\$'), 'Players'].apply(remove_dollar_sign)

# Print the updated DataFrame
FB.head(5)

,Players,Age,Matches Played,Start,Minutes,Goals,Assists,Penalties Made,Yellow Cards,Red Cards,...,Goal Defense,Tackles,Tackles Won,Challenges,Successful Challenge %,Blocks,Interceptions,Tackles + Interceptions,Clearances,Errors
0,Ederson,28,35,35,"3,150",0.0,1.0,0.0,3.0,0.0,...,0.0,3.0,1,1.0,50.0,0.0,1,4.0,10.0,2.0
1,Rodri,26,36,34,"2,911",2.0,6.0,0.0,5.0,0.0,...,0.0,67.0,41,26.0,50.0,40.0,33,100.0,43.0,1.0
2,Erling Haaland,22,35,33,"2,769",36.0,8.0,7.0,5.0,0.0,...,0.0,3.0,2,1.0,20.0,12.0,3,6.0,14.0,0.0
3,Kevin De Bruyne,31,32,28,"2,417",7.0,16.0,0.0,1.0,0.0,...,0.0,28.0,12,14.0,35.9,27.0,9,37.0,10.0,0.0
4,Ilkay Gundogan,31,31,27,"2,353",8.0,4.0,0.0,0.0,0.0,...,0.0,30.0,18,12.0,36.4,18.0,20,50.0,13.0,0.0

# Dealing With Duplicated Names

In [21]:
duplicated_names = diff[diff.duplicated(subset='Players', keep=False)]['Players']

for name, count in duplicated_names.value_counts().items():
    if count > 1:
        print(f"Duplicate name: {name}")
        players = diff[diff['Players'] == name]
        for index, player in players.iterrows():
            print(f"    {player['Players']} - Age: {player['Age']}, Value: {player['Values']}")

Duplicate name: Paulinho
    Paulinho - Age: 30, Value: 6375000.0
    Paulinho - Age: 30, Value: 6175000.0
    Paulinho - Age: 30, Value: 6100000.0
    Paulinho - Age: 30, Value: 4900000.0
    Paulinho - Age: 23, Value: 3375000.0
    Paulinho - Age: 23, Value: 3175000.0
    Paulinho - Age: 23, Value: 3100000.0
    Paulinho - Age: 23, Value: 1900000.0
    Paulinho - Age: 30, Value: -4500000.0
    Paulinho - Age: 30, Value: -6500000.0
    Paulinho - Age: 23, Value: -7500000.0
    Paulinho - Age: 23, Value: -9500000.0
Duplicate name: Danilo
    Danilo - Age: 22, Value: 24000000.0
    Danilo - Age: 22, Value: 15000000.0
    Danilo - Age: 31, Value: 11000000.0
    Danilo - Age: 24, Value: 2500000.0
    Danilo - Age: 31, Value: 2000000.0
    Danilo - Age: 24, Value: -6500000.0
Duplicate name: Vitinha
    Vitinha - Age: 23, Value: 36000000.0
    Vitinha - Age: 23, Value: 12000000.0
    Vitinha - Age: 23, Value: 12000000.0
    Vitinha - Age: 23, Value: -12000000.0
Duplicate name: Andre Silva
    Andre Silva - Age: 27, Value: 13800000.0
    Andre Silva - Age: 26, Value: 800000.0
    Andre Silva - Age: 27, Value: -17000000.0
    Andre Silva - Age: 26, Value: -30000000.0
Duplicate name: Thiago Silva
    Thiago Silva - Age: 38, Value: 1700000.0
    Thiago Silva - Age: 27, Value: -100000.0
    Thiago Silva - Age: 38, Value: -500000.0
    Thiago Silva - Age: 27, Value: -2300000.0
Duplicate name: Fernando
    Fernando - Age: 35, Value: -200000.0
    Fernando - Age: 35, Value: -1000000.0
    Fernando - Age: 31, Value: -1100000.0
    Fernando - Age: 31, Value: -1900000.0
Duplicate name: Hernani
    Hernani - Age: 22, Value: 0.0
    Hernani - Age: 31, Value: -200000.0
    Hernani - Age: 22, Value: -200000.0
    Hernani - Age: 31, Value: -400000.0
Duplicate name: Joao Mario
    Joao Mario - Age: 23, Value: 6000000.0
    Joao Mario - Age: 30, Value: 4000000.0
    Joao Mario - Age: 23, Value: 1000000.0
    Joao Mario - Age: 30, Value: -1000000.0
Duplicate name: Antony
    Antony - Age: 23, Value: 59700000.0
    Antony - Age: 23, Value: 25000000.0
    Antony - Age: 21, Value: 300000.0
    Antony - Age: 21, Value: -34400000.0
Duplicate name: Neto
    Neto - Age: 33, Value: 2250000.0
    Neto - Age: 31, Value: 0.0
    Neto - Age: 33, Value: -500000.0
    Neto - Age: 31, Value: -2750000.0
Duplicate name: Chiquinho
    Chiquinho - Age: 27, Value: 3000000.0
    Chiquinho - Age: 27, Value: 1500000.0
    Chiquinho - Age: 23, Value: -1000000.0
    Chiquinho - Age: 23, Value: -2500000.0
Duplicate name: Raul Garcia
    Raul Garcia - Age: 22, Value: 3500000.0
    Raul Garcia - Age: 37, Value: 2000000.0
    Raul Garcia - Age: 22, Value: 1500000.0
    Raul Garcia - Age: 37, Value: 0.0
Duplicate name: Bruno Fernandes
    Bruno Fernandes - Age: 28, Value: 74900000.0
    Bruno Fernandes - Age: 28, Value: -10000000.0
Duplicate name: Yusuf Erdogan
    Yusuf Erdogan - Age: 30, Value: 450000.0
    Yusuf Erdogan - Age: 30, Value: -1025000.0
Duplicate name: Ze Carlos
    Ze Carlos - Age: 21, Value: 500000.0
    Ze Carlos - Age: 24, Value: -800000.0
Duplicate name: Juan Cruz
    Juan Cruz - Age: 30, Value: 500000.0
    Juan Cruz - Age: 23, Value: -500000.0
Duplicate name: Luiz Gustavo
    Luiz Gustavo - Age: 23, Value: 0.0
    Luiz Gustavo - Age: 23, Value: -1100000.0
Duplicate name: Burak Yilmaz
    Burak Yilmaz - Age: 27, Value: 300000.0
    Burak Yilmaz - Age: 27, Value: -1100000.0
Duplicate name: Luis Suarez
    Luis Suarez - Age: 25, Value: 0.0
    Luis Suarez - Age: 25, Value: -1000000.0
Duplicate name: Bruno Rodrigues
    Bruno Rodrigues - Age: 22, Value: 600000.0
    Bruno Rodrigues - Age: 22, Value: -400000.0
Duplicate name: Luiz Felipe
    Luiz Felipe - Age: 26, Value: -1000000.0
    Luiz Felipe - Age: 26, Value: -15700000.0
Duplicate name: Andre Gomes
    Andre Gomes - Age: 29, Value: -2000000.0
    Andre Gomes - Age: 18, Value: -16000000.0
Duplicate name: Marquinhos
    Marquinhos - Age: 29, Value: -5000000.0
    Marquinhos - Age: 20, Value: -58000000.0
Duplicate name: Joao Mendes
    Joao Mendes - Age: 28, Value: 600000.0
    Joao Mendes - Age: 28, Value: 125000.0
Duplicate name: Rafa
    Rafa - Age: 30, Value: 2000000.0
    Rafa - Age: 19, Value: -19800000.0
Duplicate name: Mamadou Sylla
    Mamadou Sylla - Age: 29, Value: 850000.0
    Mamadou Sylla - Age: 29, Value: -200000.0
Duplicate name: Samu
    Samu - Age: 27, Value: 900000.0
    Samu - Age: 27, Value: 100000.0
Duplicate name: Guilherme
    Guilherme - Age: 33, Value: 1000000.0
    Guilherme - Age: 33, Value: -300000.0
Duplicate name: Vitinho
    Vitinho - Age: 23, Value: 3000000.0
    Vitinho - Age: 23, Value: -600000.0
Duplicate name: Savio
    Savio - Age: 19, Value: 4775000.0
    Savio - Age: 28, Value: 25000.0
Duplicate name: Otavio
    Otavio - Age: 28, Value: 5000000.0
    Otavio - Age: 21, Value: -29400000.0
Duplicate name: Rogerio
    Rogerio - Age: 25, Value: 5350000.0
    Rogerio - Age: 25, Value: -500000.0
Duplicate name: Abner
    Abner - Age: 27, Value: 6600000.0
    Abner - Age: 23, Value: 6600000.0
Duplicate name: Ederson
    Ederson - Age: 24, Value: 7000000.0
    Ederson - Age: 29, Value: -5000000.0
Duplicate name: Pepe
    Pepe - Age: 26, Value: 7000000.0
    Pepe - Age: 40, Value: 0.0
Duplicate name: Ben Davies
    Ben Davies - Age: 30, Value: 12500000.0
    Ben Davies - Age: 30, Value: -5000000.0
Duplicate name: Andre Almeida
    Andre Almeida - Age: 23, Value: 18500000.0
    Andre Almeida - Age: 23, Value: 15000000.0
Duplicate name: Joao Pedro
    Joao Pedro - Age: 31, Value: -6000000.0
    Joao Pedro - Age: 30, Value: -11500000.0

In [22]:
diff.drop_duplicates(subset='Players', keep=False, inplace=True)

In [19]:
duplicated_names = FB[FB.duplicated(subset='Players', keep=False)]['Players']

for name, count in duplicated_names.value_counts().items():
    if count > 1:
        print(f"Duplicate name: {name}")
        players = FB[FB['Players'] == name]
        for index, player in players.iterrows():
            print(f"    {player['Players']} - Age: {player['Age']}, Matches Played: {player['Matches Played']}")

Duplicate name: Vitinha
    Vitinha - Age: 22, Matches Played: 36
    Vitinha - Age: 22, Matches Played: 14
    Vitinha - Age: 22, Matches Played: 17
Duplicate name: Arthur
    Arthur - Age: 24, Matches Played: 28
    Arthur - Age: 24, Matches Played: 24
    Arthur - Age: 24, Matches Played: 4
Duplicate name: Joao Cancelo
    Joao Cancelo - Age: 28, Matches Played: 17
    Joao Cancelo - Age: 28, Matches Played: 15
    Joao Cancelo - Age: 28, Matches Played: 15
Duplicate name: Daley Blind
    Daley Blind - Age: 32, Matches Played: 4
    Daley Blind - Age: 32, Matches Played: 4
    Daley Blind - Age: 32, Matches Played: 13
Duplicate name: Julian Ryerson
    Julian Ryerson - Age: 24, Matches Played: 17
    Julian Ryerson - Age: 24, Matches Played: 13
    Julian Ryerson - Age: 24, Matches Played: 17
Duplicate name: Danilo
    Danilo - Age: 21, Matches Played: 13
    Danilo - Age: 31, Matches Played: 37
    Danilo - Age: 23, Matches Played: 34
Duplicate name: Marcel Sabitzer
    Marcel Sabitzer - Age: 28, Matches Played: 11
    Marcel Sabitzer - Age: 28, Matches Played: 15
    Marcel Sabitzer - Age: 28, Matches Played: 15
Duplicate name: Yann Sommer
    Yann Sommer - Age: 33, Matches Played: 19
    Yann Sommer - Age: 33, Matches Played: 10
    Yann Sommer - Age: 33, Matches Played: 19
Duplicate name: Mathys Tel
    Mathys Tel - Age: 17, Matches Played: 22
    Mathys Tel - Age: 17, Matches Played: 22
Duplicate name: Paul Wanner
    Paul Wanner - Age: 16, Matches Played: 2
    Paul Wanner - Age: 16, Matches Played: 2
Duplicate name: Jude Bellingham
    Jude Bellingham - Age: 19, Matches Played: 31
    Jude Bellingham - Age: 19, Matches Played: 31
Duplicate name: Julian Brandt
    Julian Brandt - Age: 26, Matches Played: 32
    Julian Brandt - Age: 26, Matches Played: 32
Duplicate name: Gregor Kobel
    Gregor Kobel - Age: 24, Matches Played: 27
    Gregor Kobel - Age: 24, Matches Played: 27
Duplicate name: Nico Schlotterbeck
    Nico Schlotterbeck - Age: 22, Matches Played: 28
    Nico Schlotterbeck - Age: 22, Matches Played: 28
Duplicate name: Raphael Guerreiro
    Raphael Guerreiro - Age: 28, Matches Played: 27
    Raphael Guerreiro - Age: 28, Matches Played: 27
Duplicate name: Donyell Malen
    Donyell Malen - Age: 23, Matches Played: 26
    Donyell Malen - Age: 23, Matches Played: 26
Duplicate name: Mats Hummels
    Mats Hummels - Age: 33, Matches Played: 30
    Mats Hummels - Age: 33, Matches Played: 30
Duplicate name: Niklas Sule
    Niklas Sule - Age: 26, Matches Played: 29
    Niklas Sule - Age: 26, Matches Played: 29
Duplicate name: Ryan Gravenberch
    Ryan Gravenberch - Age: 20, Matches Played: 24
    Ryan Gravenberch - Age: 20, Matches Played: 24
Duplicate name: Emre Can
    Emre Can - Age: 28, Matches Played: 27
    Emre Can - Age: 28, Matches Played: 27
Duplicate name: Karim Adeyemi
    Karim Adeyemi - Age: 20, Matches Played: 24
    Karim Adeyemi - Age: 20, Matches Played: 24
Duplicate name: Salih Ozcan
    Salih Ozcan - Age: 24, Matches Played: 26
    Salih Ozcan - Age: 24, Matches Played: 26
Duplicate name: Marius Wolf
    Marius Wolf - Age: 27, Matches Played: 25
    Marius Wolf - Age: 27, Matches Played: 25
Duplicate name: Sebastien Haller
    Sebastien Haller - Age: 28, Matches Played: 19
    Sebastien Haller - Age: 28, Matches Played: 19
Duplicate name: Marco Reus
    Marco Reus - Age: 33, Matches Played: 25
    Marco Reus - Age: 33, Matches Played: 25
Duplicate name: Youssoufa Moukoko
    Youssoufa Moukoko - Age: 17, Matches Played: 26
    Youssoufa Moukoko - Age: 17, Matches Played: 26
Duplicate name: Sven Ulreich
    Sven Ulreich - Age: 33, Matches Played: 3
    Sven Ulreich - Age: 33, Matches Played: 3
Duplicate name: Ederson
    Ederson - Age: 28, Matches Played: 35
    Ederson - Age: 23, Matches Played: 35
Duplicate name: Josip Stanisic
    Josip Stanisic - Age: 22, Matches Played: 14
    Josip Stanisic - Age: 22, Matches Played: 14
Duplicate name: Alexander Meyer
    Alexander Meyer - Age: 31, Matches Played: 7
    Alexander Meyer - Age: 31, Matches Played: 7
Duplicate name: Cyril Ngonge
    Cyril Ngonge - Age: 22, Matches Played: 14
    Cyril Ngonge - Age: 22, Matches Played: 12
Duplicate name: Alex Ferrari
    Alex Ferrari - Age: 28, Matches Played: 16
    Alex Ferrari - Age: 28, Matches Played: 12
Duplicate name: Ionut Radu
    Ionut Radu - Age: 25, Matches Played: 9
    Ionut Radu - Age: 25, Matches Played: 17
Duplicate name: Joshua Kimmich
    Joshua Kimmich - Age: 27, Matches Played: 33
    Joshua Kimmich - Age: 27, Matches Played: 33
Duplicate name: Benjamin Pavard
    Benjamin Pavard - Age: 26, Matches Played: 30
    Benjamin Pavard - Age: 26, Matches Played: 30
Duplicate name: Matthijs Ligt
    Matthijs Ligt - Age: 22, Matches Played: 31
    Matthijs Ligt - Age: 22, Matches Played: 31
Duplicate name: Dayot Upamecano
    Dayot Upamecano - Age: 23, Matches Played: 29
    Dayot Upamecano - Age: 23, Matches Played: 29
Duplicate name: Jamal Musiala
    Jamal Musiala - Age: 19, Matches Played: 33
    Jamal Musiala - Age: 19, Matches Played: 33
Duplicate name: Alphonso Davies
    Alphonso Davies - Age: 21, Matches Played: 26
    Alphonso Davies - Age: 21, Matches Played: 26
Duplicate name: Serge Gnabry
    Serge Gnabry - Age: 27, Matches Played: 34
    Serge Gnabry - Age: 27, Matches Played: 34
Duplicate name: Leon Goretzka
    Leon Goretzka - Age: 27, Matches Played: 27
    Leon Goretzka - Age: 27, Matches Played: 27
Duplicate name: Thomas Muller
    Thomas Muller - Age: 32, Matches Played: 27
    Thomas Muller - Age: 32, Matches Played: 27
Duplicate name: Leroy Sane
    Leroy Sane - Age: 26, Matches Played: 32
    Leroy Sane - Age: 26, Matches Played: 32
Duplicate name: Sadio Mane
    Sadio Mane - Age: 30, Matches Played: 25
    Sadio Mane - Age: 30, Matches Played: 25
Duplicate name: Kingsley Coman
    Kingsley Coman - Age: 26, Matches Played: 24
    Kingsley Coman - Age: 26, Matches Played: 24
Duplicate name: Eric Maxim Choupo-Moting
    Eric Maxim Choupo-Moting - Age: 33, Matches Played: 19
    Eric Maxim Choupo-Moting - Age: 33, Matches Played: 19
Duplicate name: Manuel Neuer
    Manuel Neuer - Age: 36, Matches Played: 12
    Manuel Neuer - Age: 36, Matches Played: 12
Duplicate name: Noussair Mazraoui
    Noussair Mazraoui - Age: 24, Matches Played: 19
    Noussair Mazraoui - Age: 24, Matches Played: 19
Duplicate name: Lucas Hernandez
    Lucas Hernandez - Age: 26, Matches Played: 7
    Lucas Hernandez - Age: 26, Matches Played: 7
Duplicate name: Anthony Modeste
    Anthony Modeste - Age: 34, Matches Played: 19
    Anthony Modeste - Age: 34, Matches Played: 19
Duplicate name: Gio Reyna
    Gio Reyna - Age: 19, Matches Played: 22
    Gio Reyna - Age: 19, Matches Played: 22
Duplicate name: Thomas Meunier
    Thomas Meunier - Age: 30, Matches Played: 10
    Thomas Meunier - Age: 30, Matches Played: 10
Duplicate name: Adrien Thomasson
    Adrien Thomasson - Age: 28, Matches Played: 20
    Adrien Thomasson - Age: 28, Matches Played: 15
Duplicate name: Bamba Dieng
    Bamba Dieng - Age: 22, Matches Played: 10
    Bamba Dieng - Age: 22, Matches Played: 15
Duplicate name: Azzedine Ounahi
    Azzedine Ounahi - Age: 22, Matches Played: 7
    Azzedine Ounahi - Age: 22, Matches Played: 15
Duplicate name: Amine Gouiri
    Amine Gouiri - Age: 22, Matches Played: 33
    Amine Gouiri - Age: 22, Matches Played: 3
Duplicate name: Karl Toko Ekambi
    Karl Toko Ekambi - Age: 29, Matches Played: 17
    Karl Toko Ekambi - Age: 29, Matches Played: 19
Duplicate name: Gaetan Laborde
    Gaetan Laborde - Age: 28, Matches Played: 4
    Gaetan Laborde - Age: 28, Matches Played: 33
Duplicate name: Akim Zedadka
    Akim Zedadka - Age: 27, Matches Played: 8
    Akim Zedadka - Age: 27, Matches Played: 20
Duplicate name: Chrislain Matsima
    Chrislain Matsima - Age: 20, Matches Played: 8
    Chrislain Matsima - Age: 20, Matches Played: 6
Duplicate name: Amin Sarr
    Amin Sarr - Age: 21, Matches Played: 13
    Amin Sarr - Age: 21, Matches Played: 19
Duplicate name: Romain Faivre
    Romain Faivre - Age: 24, Matches Played: 10
    Romain Faivre - Age: 24, Matches Played: 16
Duplicate name: Terem Moffi
    Terem Moffi - Age: 23, Matches Played: 16
    Terem Moffi - Age: 23, Matches Played: 18
Duplicate name: Andy Delort
    Andy Delort - Age: 30, Matches Played: 14
    Andy Delort - Age: 30, Matches Played: 12
Duplicate name: Banzouzi Locko
    Banzouzi Locko - Age: 20, Matches Played: 15
    Banzouzi Locko - Age: 20, Matches Played: 7
Duplicate name: Issiaga Sylla
    Issiaga Sylla - Age: 28, Matches Played: 15
    Issiaga Sylla - Age: 28, Matches Played: 17
Duplicate name: Youcef Belaili
    Youcef Belaili - Age: 30, Matches Played: 6
    Youcef Belaili - Age: 30, Matches Played: 17
Duplicate name: Pepe
    Pepe - Age: 25, Matches Played: 34
    Pepe - Age: 39, Matches Played: 24
Duplicate name: Anderson
    Anderson - Age: 24, Matches Played: 30
    Anderson - Age: 24, Matches Played: 6
Duplicate name: Costinha
    Costinha - Age: 22, Matches Played: 33
    Costinha - Age: 29, Matches Played: 13
Duplicate name: Sven Mijnans
    Sven Mijnans - Age: 22, Matches Played: 15
    Sven Mijnans - Age: 22, Matches Played: 19
Duplicate name: Mats Seuntjens
    Mats Seuntjens - Age: 30, Matches Played: 19
    Mats Seuntjens - Age: 30, Matches Played: 12
Duplicate name: Ignatius Ganago
    Ignatius Ganago - Age: 23, Matches Played: 4
    Ignatius Ganago - Age: 23, Matches Played: 28
Duplicate name: Myziane Maolida
    Myziane Maolida - Age: 23, Matches Played: 3
    Myziane Maolida - Age: 23, Matches Played: 9
Duplicate name: Ondrej Duda
    Ondrej Duda - Age: 27, Matches Played: 15
    Ondrej Duda - Age: 27, Matches Played: 13
Duplicate name: Jere Uronen
    Jere Uronen - Age: 28, Matches Played: 11
    Jere Uronen - Age: 28, Matches Played: 6
Duplicate name: Jamie Bynoe-Gittens
    Jamie Bynoe-Gittens - Age: 17, Matches Played: 15
    Jamie Bynoe-Gittens - Age: 17, Matches Played: 15
Duplicate name: Mahmoud Dahoud
    Mahmoud Dahoud - Age: 26, Matches Played: 9
    Mahmoud Dahoud - Age: 26, Matches Played: 9
Duplicate name: Thorgan Hazard
    Thorgan Hazard - Age: 29, Matches Played: 14
    Thorgan Hazard - Age: 29, Matches Played: 14
Duplicate name: Felix Passlack
    Felix Passlack - Age: 24, Matches Played: 3
    Felix Passlack - Age: 24, Matches Played: 3
Duplicate name: Soumaila Coulibaly
    Soumaila Coulibaly - Age: 18, Matches Played: 1
    Soumaila Coulibaly - Age: 18, Matches Played: 1
Duplicate name: Andre Silva
    Andre Silva - Age: 26, Matches Played: 31
    Andre Silva - Age: 25, Matches Played: 23
Duplicate name: Jerome Roussillon
    Jerome Roussillon - Age: 29, Matches Played: 16
    Jerome Roussillon - Age: 29, Matches Played: 4
Duplicate name: Genki Haraguchi
    Genki Haraguchi - Age: 31, Matches Played: 11
    Genki Haraguchi - Age: 31, Matches Played: 11
Duplicate name: Paulinho
    Paulinho - Age: 22, Matches Played: 4
    Paulinho - Age: 29, Matches Played: 22
Duplicate name: Philipp Max
    Philipp Max - Age: 28, Matches Played: 10
    Philipp Max - Age: 28, Matches Played: 14
Duplicate name: Maximilian Philipp
    Maximilian Philipp - Age: 28, Matches Played: 3
    Maximilian Philipp - Age: 28, Matches Played: 15
Duplicate name: Nicolas Cozza
    Nicolas Cozza - Age: 23, Matches Played: 5
    Nicolas Cozza - Age: 23, Matches Played: 17
Duplicate name: Ludovic Ajorque
    Ludovic Ajorque - Age: 28, Matches Played: 17
    Ludovic Ajorque - Age: 28, Matches Played: 13
Duplicate name: Angelo Fulgini
    Angelo Fulgini - Age: 25, Matches Played: 16
    Angelo Fulgini - Age: 25, Matches Played: 17
Duplicate name: Julian Weigl
    Julian Weigl - Age: 26, Matches Played: 23
    Julian Weigl - Age: 26, Matches Played: 2
Duplicate name: Jonas Omlin
    Jonas Omlin - Age: 28, Matches Played: 15
    Jonas Omlin - Age: 28, Matches Played: 14
Duplicate name: Nathan N'Goumou
    Nathan N'Goumou - Age: 22, Matches Played: 20
    Nathan N'Goumou - Age: 22, Matches Played: 1
Duplicate name: Davie Selke
    Davie Selke - Age: 27, Matches Played: 17
    Davie Selke - Age: 27, Matches Played: 13
Duplicate name: Florian Niederlechner
    Florian Niederlechner - Age: 31, Matches Played: 14
    Florian Niederlechner - Age: 31, Matches Played: 16
Duplicate name: Koray Gunter
    Koray Gunter - Age: 27, Matches Played: 13
    Koray Gunter - Age: 27, Matches Played: 10
Duplicate name: Sam Lammers
    Sam Lammers - Age: 25, Matches Played: 14
    Sam Lammers - Age: 25, Matches Played: 19
Duplicate name: Kristijan Bistrovic
    Kristijan Bistrovic - Age: 24, Matches Played: 11
    Kristijan Bistrovic - Age: 24, Matches Played: 13
Duplicate name: Mads Bech Sorensen
    Mads Bech Sorensen - Age: 23, Matches Played: 4
    Mads Bech Sorensen - Age: 23, Matches Played: 11
Duplicate name: Sasa Lukic
    Sasa Lukic - Age: 25, Matches Played: 12
    Sasa Lukic - Age: 25, Matches Played: 16
Duplicate name: Naouirou Ahamada
    Naouirou Ahamada - Age: 20, Matches Played: 8
    Naouirou Ahamada - Age: 20, Matches Played: 17
Duplicate name: Enzo Fernandez
    Enzo Fernandez - Age: 21, Matches Played: 18
    Enzo Fernandez - Age: 21, Matches Played: 17
Duplicate name: Joao Felix
    Joao Felix - Age: 22, Matches Played: 16
    Joao Felix - Age: 22, Matches Played: 14
Duplicate name: Benoit Badiashile
    Benoit Badiashile - Age: 21, Matches Played: 11
    Benoit Badiashile - Age: 21, Matches Played: 11
Duplicate name: Matheus Nunes
    Matheus Nunes - Age: 23, Matches Played: 34
    Matheus Nunes - Age: 23, Matches Played: 2
Duplicate name: Craig Dawson
    Craig Dawson - Age: 32, Matches Played: 17
    Craig Dawson - Age: 32, Matches Played: 8
Duplicate name: Mario Lemina
    Mario Lemina - Age: 28, Matches Played: 19
    Mario Lemina - Age: 28, Matches Played: 14
Duplicate name: Matheus Cunha
    Matheus Cunha - Age: 23, Matches Played: 17
    Matheus Cunha - Age: 23, Matches Played: 11
Duplicate name: Pablo Sarabia
    Pablo Sarabia - Age: 30, Matches Played: 13
    Pablo Sarabia - Age: 30, Matches Played: 14
Duplicate name: Goncalo Guedes
    Goncalo Guedes - Age: 25, Matches Played: 13
    Goncalo Guedes - Age: 25, Matches Played: 12
Duplicate name: Neto
    Neto - Age: 33, Matches Played: 27
    Neto - Age: 30, Matches Played: 27
Duplicate name: Dango Ouattara
    Dango Ouattara - Age: 20, Matches Played: 19
    Dango Ouattara - Age: 20, Matches Played: 18
Duplicate name: Hamed Junior Traore
    Hamed Junior Traore - Age: 22, Matches Played: 7
    Hamed Junior Traore - Age: 22, Matches Played: 11
Duplicate name: Felipe
    Felipe - Age: 33, Matches Played: 16
    Felipe - Age: 33, Matches Played: 3
Duplicate name: Wout Faes
    Wout Faes - Age: 24, Matches Played: 31
    Wout Faes - Age: 24, Matches Played: 3
Duplicate name: Tete
    Tete - Age: 22, Matches Played: 13
    Tete - Age: 22, Matches Played: 17
Duplicate name: Ayoze Perez
    Ayoze Perez - Age: 29, Matches Played: 8
    Ayoze Perez - Age: 29, Matches Played: 19
Duplicate name: Weston McKennie
    Weston McKennie - Age: 23, Matches Played: 19
    Weston McKennie - Age: 23, Matches Played: 15
Duplicate name: Daniel James
    Daniel James - Age: 24, Matches Played: 20
    Daniel James - Age: 24, Matches Played: 4
Duplicate name: Kevin Schade
    Kevin Schade - Age: 20, Matches Played: 18
    Kevin Schade - Age: 20, Matches Played: 8
Duplicate name: Georginio Rutter
    Georginio Rutter - Age: 20, Matches Played: 11
    Georginio Rutter - Age: 20, Matches Played: 15
Duplicate name: Arnaut Danjuma
    Arnaut Danjuma - Age: 25, Matches Played: 9
    Arnaut Danjuma - Age: 25, Matches Played: 10
Duplicate name: Leandro Trossard
    Leandro Trossard - Age: 27, Matches Played: 20
    Leandro Trossard - Age: 27, Matches Played: 16
Duplicate name: Jorginho
    Jorginho - Age: 30, Matches Played: 14
    Jorginho - Age: 30, Matches Played: 18
Duplicate name: Jakub Kiwior
    Jakub Kiwior - Age: 22, Matches Played: 7
    Jakub Kiwior - Age: 22, Matches Played: 17
Duplicate name: Albert Sambi Lokonga
    Albert Sambi Lokonga - Age: 22, Matches Played: 6
    Albert Sambi Lokonga - Age: 22, Matches Played: 9
Duplicate name: Cedric Soares
    Cedric Soares - Age: 30, Matches Played: 2
    Cedric Soares - Age: 30, Matches Played: 6
Duplicate name: Marquinhos
    Marquinhos - Age: 19, Matches Played: 1
    Marquinhos - Age: 28, Matches Played: 33
Duplicate name: Antony
    Antony - Age: 20, Matches Played: 25
    Antony - Age: 20, Matches Played: 33
Duplicate name: Alexander Isak
    Alexander Isak - Age: 22, Matches Played: 22
    Alexander Isak - Age: 22, Matches Played: 2
Duplicate name: Anthony Gordon
    Anthony Gordon - Age: 21, Matches Played: 16
    Anthony Gordon - Age: 21, Matches Played: 16
Duplicate name: Chris Wood
    Chris Wood - Age: 30, Matches Played: 18
    Chris Wood - Age: 30, Matches Played: 7
Duplicate name: Jonjo Shelvey
    Jonjo Shelvey - Age: 30, Matches Played: 3
    Jonjo Shelvey - Age: 30, Matches Played: 8
Duplicate name: Cody Gakpo
    Cody Gakpo - Age: 23, Matches Played: 21
    Cody Gakpo - Age: 23, Matches Played: 14
Duplicate name: Alex Moreno
    Alex Moreno - Age: 29, Matches Played: 19
    Alex Moreno - Age: 29, Matches Played: 15
Duplicate name: Danny Ings
    Danny Ings - Age: 30, Matches Played: 18
    Danny Ings - Age: 30, Matches Played: 17
Duplicate name: Leander Dendoncker
    Leander Dendoncker - Age: 27, Matches Played: 20
    Leander Dendoncker - Age: 27, Matches Played: 4
Duplicate name: Jan Bednarek
    Jan Bednarek - Age: 26, Matches Played: 3
    Jan Bednarek - Age: 26, Matches Played: 20
Duplicate name: Ludwig Augustinsson
    Ludwig Augustinsson - Age: 28, Matches Played: 3
    Ludwig Augustinsson - Age: 28, Matches Played: 4
Duplicate name: Pedro Porro
    Pedro Porro - Age: 22, Matches Played: 15
    Pedro Porro - Age: 22, Matches Played: 14
Duplicate name: Bryan Gil
    Bryan Gil - Age: 21, Matches Played: 4
    Bryan Gil - Age: 21, Matches Played: 17
Duplicate name: Diego Llorente
    Diego Llorente - Age: 28, Matches Played: 8
    Diego Llorente - Age: 28, Matches Played: 9
Duplicate name: Kamaldeen Sulemana
    Kamaldeen Sulemana - Age: 20, Matches Played: 18
    Kamaldeen Sulemana - Age: 20, Matches Played: 14
Duplicate name: Rodri
    Rodri - Age: 26, Matches Played: 36
    Rodri - Age: 22, Matches Played: 30
Duplicate name: Pierluigi Gollini
    Pierluigi Gollini - Age: 27, Matches Played: 4
    Pierluigi Gollini - Age: 27, Matches Played: 3
Duplicate name: Luca Pellegrini
    Luca Pellegrini - Age: 23, Matches Played: 7
    Luca Pellegrini - Age: 23, Matches Played: 9
Duplicate name: Brandon Soppy
    Brandon Soppy - Age: 20, Matches Played: 15
    Brandon Soppy - Age: 20, Matches Played: 1
Duplicate name: Ruslan Malinovskyi
    Ruslan Malinovskyi - Age: 29, Matches Played: 15
    Ruslan Malinovskyi - Age: 29, Matches Played: 20
Duplicate name: Nadir Zortea
    Nadir Zortea - Age: 23, Matches Played: 9
    Nadir Zortea - Age: 23, Matches Played: 10
Duplicate name: Mohamed Camara
    Mohamed Camara - Age: 25, Matches Played: 15
    Mohamed Camara - Age: 22, Matches Played: 29
Duplicate name: Filip Kostic
    Filip Kostic - Age: 29, Matches Played: 37
    Filip Kostic - Age: 29, Matches Played: 1
Duplicate name: Arkadiusz Milik
    Arkadiusz Milik - Age: 28, Matches Played: 27
    Arkadiusz Milik - Age: 28, Matches Played: 2
Duplicate name: Leandro Paredes
    Leandro Paredes - Age: 28, Matches Played: 25
    Leandro Paredes - Age: 28, Matches Played: 3
Duplicate name: Youssef Maleh
    Youssef Maleh - Age: 23, Matches Played: 7
    Youssef Maleh - Age: 23, Matches Played: 17
Duplicate name: Giorgos Kyriakopoulos
    Giorgos Kyriakopoulos - Age: 26, Matches Played: 12
    Giorgos Kyriakopoulos - Age: 26, Matches Played: 12
Duplicate name: Ivan Ilic
    Ivan Ilic - Age: 21, Matches Played: 14
    Ivan Ilic - Age: 21, Matches Played: 11
Duplicate name: Andrew Gravillon
    Andrew Gravillon - Age: 24, Matches Played: 7

In [25]:
FB.sort_values('Matches Played', ascending=False, inplace=True)

In [26]:
duplicated_names = FB[FB.duplicated(subset='Players', keep=False)]['Players']

for name, count in duplicated_names.value_counts().items():
    if count > 1:
        print(f"Duplicate name: {name}")
        players = FB[FB['Players'] == name]
        for index, player in players.iterrows():
            print(f"    {player['Players']} - Age: {player['Age']}, Matches Played: {player['Matches Played']}")

Duplicate name: Danilo
    Danilo - Age: 31, Matches Played: 37
    Danilo - Age: 23, Matches Played: 34
    Danilo - Age: 21, Matches Played: 13
Duplicate name: Vitinha
    Vitinha - Age: 22, Matches Played: 36
    Vitinha - Age: 22, Matches Played: 17
    Vitinha - Age: 22, Matches Played: 14
Duplicate name: Marcel Sabitzer
    Marcel Sabitzer - Age: 28, Matches Played: 15
    Marcel Sabitzer - Age: 28, Matches Played: 15
    Marcel Sabitzer - Age: 28, Matches Played: 11
Duplicate name: Arthur
    Arthur - Age: 24, Matches Played: 28
    Arthur - Age: 24, Matches Played: 24
    Arthur - Age: 24, Matches Played: 4
Duplicate name: Yann Sommer
    Yann Sommer - Age: 33, Matches Played: 19
    Yann Sommer - Age: 33, Matches Played: 19
    Yann Sommer - Age: 33, Matches Played: 10
Duplicate name: Joao Cancelo
    Joao Cancelo - Age: 28, Matches Played: 17
    Joao Cancelo - Age: 28, Matches Played: 15
    Joao Cancelo - Age: 28, Matches Played: 15
Duplicate name: Julian Ryerson
    Julian Ryerson - Age: 24, Matches Played: 17
    Julian Ryerson - Age: 24, Matches Played: 17
    Julian Ryerson - Age: 24, Matches Played: 13
Duplicate name: Daley Blind
    Daley Blind - Age: 32, Matches Played: 13
    Daley Blind - Age: 32, Matches Played: 4
    Daley Blind - Age: 32, Matches Played: 4
Duplicate name: Filip Kostic
    Filip Kostic - Age: 29, Matches Played: 37
    Filip Kostic - Age: 29, Matches Played: 1
Duplicate name: Romain Faivre
    Romain Faivre - Age: 24, Matches Played: 16
    Romain Faivre - Age: 24, Matches Played: 10
Duplicate name: Jean-Victor Makengo
    Jean-Victor Makengo - Age: 24, Matches Played: 16
    Jean-Victor Makengo - Age: 24, Matches Played: 15
Duplicate name: Pape Gueye
    Pape Gueye - Age: 23, Matches Played: 16
    Pape Gueye - Age: 23, Matches Played: 14
Duplicate name: Sasa Lukic
    Sasa Lukic - Age: 25, Matches Played: 16
    Sasa Lukic - Age: 25, Matches Played: 12
Duplicate name: Gonzalo Villar
    Gonzalo Villar - Age: 24, Matches Played: 16
    Gonzalo Villar - Age: 24, Matches Played: 15
Duplicate name: Felipe
    Felipe - Age: 33, Matches Played: 16
    Felipe - Age: 33, Matches Played: 3
Duplicate name: Brandon Soppy
    Brandon Soppy - Age: 20, Matches Played: 15
    Brandon Soppy - Age: 20, Matches Played: 1
Duplicate name: Joao Felix
    Joao Felix - Age: 22, Matches Played: 16
    Joao Felix - Age: 22, Matches Played: 14
Duplicate name: Florian Niederlechner
    Florian Niederlechner - Age: 31, Matches Played: 16
    Florian Niederlechner - Age: 31, Matches Played: 14
Duplicate name: Jerome Roussillon
    Jerome Roussillon - Age: 29, Matches Played: 16
    Jerome Roussillon - Age: 29, Matches Played: 4
Duplicate name: Azzedine Ounahi
    Azzedine Ounahi - Age: 22, Matches Played: 15
    Azzedine Ounahi - Age: 22, Matches Played: 7
Duplicate name: Bamba Dieng
    Bamba Dieng - Age: 22, Matches Played: 15
    Bamba Dieng - Age: 22, Matches Played: 10
Duplicate name: Banzouzi Locko
    Banzouzi Locko - Age: 20, Matches Played: 15
    Banzouzi Locko - Age: 20, Matches Played: 7
Duplicate name: Maximilian Philipp
    Maximilian Philipp - Age: 28, Matches Played: 15
    Maximilian Philipp - Age: 28, Matches Played: 3
Duplicate name: Mike te Wierik
    Mike te Wierik - Age: 30, Matches Played: 15
    Mike te Wierik - Age: 30, Matches Played: 14
Duplicate name: Jamie Bynoe-Gittens
    Jamie Bynoe-Gittens - Age: 17, Matches Played: 15
    Jamie Bynoe-Gittens - Age: 17, Matches Played: 15
Duplicate name: Georginio Rutter
    Georginio Rutter - Age: 20, Matches Played: 15
    Georginio Rutter - Age: 20, Matches Played: 11
Duplicate name: Anthony Gordon
    Anthony Gordon - Age: 21, Matches Played: 16
    Anthony Gordon - Age: 21, Matches Played: 16
Duplicate name: Ramon Terrats
    Ramon Terrats - Age: 21, Matches Played: 16
    Ramon Terrats - Age: 21, Matches Played: 8
Duplicate name: Fernando Pacheco
    Fernando Pacheco - Age: 30, Matches Played: 16
    Fernando Pacheco - Age: 30, Matches Played: 1
Duplicate name: Issiaga Sylla
    Issiaga Sylla - Age: 28, Matches Played: 17
    Issiaga Sylla - Age: 28, Matches Played: 15
Duplicate name: Chris Wood
    Chris Wood - Age: 30, Matches Played: 18
    Chris Wood - Age: 30, Matches Played: 7
Duplicate name: Jorginho
    Jorginho - Age: 30, Matches Played: 18
    Jorginho - Age: 30, Matches Played: 14
Duplicate name: Davie Selke
    Davie Selke - Age: 27, Matches Played: 17
    Davie Selke - Age: 27, Matches Played: 13
Duplicate name: Youcef Belaili
    Youcef Belaili - Age: 30, Matches Played: 17
    Youcef Belaili - Age: 30, Matches Played: 6
Duplicate name: Bryan Gil
    Bryan Gil - Age: 21, Matches Played: 17
    Bryan Gil - Age: 21, Matches Played: 4
Duplicate name: Sergi Guardiola
    Sergi Guardiola - Age: 31, Matches Played: 17
    Sergi Guardiola - Age: 31, Matches Played: 14
Duplicate name: Naouirou Ahamada
    Naouirou Ahamada - Age: 20, Matches Played: 17
    Naouirou Ahamada - Age: 20, Matches Played: 8
Duplicate name: Nicolas Cozza
    Nicolas Cozza - Age: 23, Matches Played: 17
    Nicolas Cozza - Age: 23, Matches Played: 5
Duplicate name: Ionut Radu
    Ionut Radu - Age: 25, Matches Played: 17
    Ionut Radu - Age: 25, Matches Played: 9
Duplicate name: Alex Ferrari
    Alex Ferrari - Age: 28, Matches Played: 16
    Alex Ferrari - Age: 28, Matches Played: 12
Duplicate name: Jakub Kiwior
    Jakub Kiwior - Age: 22, Matches Played: 17
    Jakub Kiwior - Age: 22, Matches Played: 7
Duplicate name: Ludovic Ajorque
    Ludovic Ajorque - Age: 28, Matches Played: 17
    Ludovic Ajorque - Age: 28, Matches Played: 13
Duplicate name: Youssef Maleh
    Youssef Maleh - Age: 23, Matches Played: 17
    Youssef Maleh - Age: 23, Matches Played: 7
Duplicate name: Craig Dawson
    Craig Dawson - Age: 32, Matches Played: 17
    Craig Dawson - Age: 32, Matches Played: 8
Duplicate name: Tete
    Tete - Age: 22, Matches Played: 17
    Tete - Age: 22, Matches Played: 13
Duplicate name: Matheus Cunha
    Matheus Cunha - Age: 23, Matches Played: 17
    Matheus Cunha - Age: 23, Matches Played: 11
Duplicate name: Angelo Fulgini
    Angelo Fulgini - Age: 25, Matches Played: 17
    Angelo Fulgini - Age: 25, Matches Played: 16
Duplicate name: Jonas Omlin
    Jonas Omlin - Age: 28, Matches Played: 15
    Jonas Omlin - Age: 28, Matches Played: 14
Duplicate name: Bartosz Bereszynski
    Bartosz Bereszynski - Age: 30, Matches Played: 15
    Bartosz Bereszynski - Age: 30, Matches Played: 3
Duplicate name: Pedro Porro
    Pedro Porro - Age: 22, Matches Played: 15
    Pedro Porro - Age: 22, Matches Played: 14
Duplicate name: Ondrej Duda
    Ondrej Duda - Age: 27, Matches Played: 15
    Ondrej Duda - Age: 27, Matches Played: 13
Duplicate name: Memphis
    Memphis - Age: 28, Matches Played: 8
    Memphis - Age: 28, Matches Played: 2
Duplicate name: Nadir Zortea
    Nadir Zortea - Age: 23, Matches Played: 10
    Nadir Zortea - Age: 23, Matches Played: 9
Duplicate name: Arnaut Danjuma
    Arnaut Danjuma - Age: 25, Matches Played: 10
    Arnaut Danjuma - Age: 25, Matches Played: 9
Duplicate name: Carmona
    Carmona - Age: 20, Matches Played: 10
    Carmona - Age: 20, Matches Played: 9
Duplicate name: Hector Bellerin
    Hector Bellerin - Age: 27, Matches Played: 10
    Hector Bellerin - Age: 27, Matches Played: 3
Duplicate name: Mahmoud Dahoud
    Mahmoud Dahoud - Age: 26, Matches Played: 9
    Mahmoud Dahoud - Age: 26, Matches Played: 9
Duplicate name: Diego Llorente
    Diego Llorente - Age: 28, Matches Played: 9
    Diego Llorente - Age: 28, Matches Played: 8
Duplicate name: Luca Pellegrini
    Luca Pellegrini - Age: 23, Matches Played: 9
    Luca Pellegrini - Age: 23, Matches Played: 7
Duplicate name: Albert Sambi Lokonga
    Albert Sambi Lokonga - Age: 22, Matches Played: 9
    Albert Sambi Lokonga - Age: 22, Matches Played: 6
Duplicate name: Myziane Maolida
    Myziane Maolida - Age: 23, Matches Played: 9
    Myziane Maolida - Age: 23, Matches Played: 3
Duplicate name: Jonjo Shelvey
    Jonjo Shelvey - Age: 30, Matches Played: 8
    Jonjo Shelvey - Age: 30, Matches Played: 3
Duplicate name: Enzo Fernandez
    Enzo Fernandez - Age: 21, Matches Played: 18
    Enzo Fernandez - Age: 21, Matches Played: 17
Duplicate name: Chrislain Matsima
    Chrislain Matsima - Age: 20, Matches Played: 8
    Chrislain Matsima - Age: 20, Matches Played: 6
Duplicate name: Lucas Hernandez
    Lucas Hernandez - Age: 26, Matches Played: 7
    Lucas Hernandez - Age: 26, Matches Played: 7
Duplicate name: Alexander Meyer
    Alexander Meyer - Age: 31, Matches Played: 7
    Alexander Meyer - Age: 31, Matches Played: 7
Duplicate name: Cedric Soares
    Cedric Soares - Age: 30, Matches Played: 6
    Cedric Soares - Age: 30, Matches Played: 2
Duplicate name: Pierluigi Gollini
    Pierluigi Gollini - Age: 27, Matches Played: 4
    Pierluigi Gollini - Age: 27, Matches Played: 3
Duplicate name: Ludwig Augustinsson
    Ludwig Augustinsson - Age: 28, Matches Played: 4
    Ludwig Augustinsson - Age: 28, Matches Played: 3
Duplicate name: Sven Ulreich
    Sven Ulreich - Age: 33, Matches Played: 3
    Sven Ulreich - Age: 33, Matches Played: 3
Duplicate name: Felix Passlack
    Felix Passlack - Age: 24, Matches Played: 3
    Felix Passlack - Age: 24, Matches Played: 3
Duplicate name: Paul Wanner
    Paul Wanner - Age: 16, Matches Played: 2
    Paul Wanner - Age: 16, Matches Played: 2
Duplicate name: Thomas Meunier
    Thomas Meunier - Age: 30, Matches Played: 10
    Thomas Meunier - Age: 30, Matches Played: 10
Duplicate name: Hamed Junior Traore
    Hamed Junior Traore - Age: 22, Matches Played: 11
    Hamed Junior Traore - Age: 22, Matches Played: 7
Duplicate name: Benoit Badiashile
    Benoit Badiashile - Age: 21, Matches Played: 11
    Benoit Badiashile - Age: 21, Matches Played: 11
Duplicate name: Genki Haraguchi
    Genki Haraguchi - Age: 31, Matches Played: 11
    Genki Haraguchi - Age: 31, Matches Played: 11
Duplicate name: Pablo Sarabia
    Pablo Sarabia - Age: 30, Matches Played: 14
    Pablo Sarabia - Age: 30, Matches Played: 13
Duplicate name: Ronael Pierre-Gabriel
    Ronael Pierre-Gabriel - Age: 24, Matches Played: 14
    Ronael Pierre-Gabriel - Age: 24, Matches Played: 8
Duplicate name: Randy Ntekja
    Randy Ntekja - Age: 24, Matches Played: 14
    Randy Ntekja - Age: 24, Matches Played: 10
Duplicate name: Josip Stanisic
    Josip Stanisic - Age: 22, Matches Played: 14
    Josip Stanisic - Age: 22, Matches Played: 14
Duplicate name: Thorgan Hazard
    Thorgan Hazard - Age: 29, Matches Played: 14
    Thorgan Hazard - Age: 29, Matches Played: 14
Duplicate name: Gonzalo Escalante
    Gonzalo Escalante - Age: 29, Matches Played: 14
    Gonzalo Escalante - Age: 29, Matches Played: 9
Duplicate name: Roger Marti
    Roger Marti - Age: 31, Matches Played: 14
    Roger Marti - Age: 31, Matches Played: 12
Duplicate name: Andy Delort
    Andy Delort - Age: 30, Matches Played: 14
    Andy Delort - Age: 30, Matches Played: 12
Duplicate name: Cyril Ngonge
    Cyril Ngonge - Age: 22, Matches Played: 14
    Cyril Ngonge - Age: 22, Matches Played: 12
Duplicate name: Ivan Ilic
    Ivan Ilic - Age: 21, Matches Played: 14
    Ivan Ilic - Age: 21, Matches Played: 11
Duplicate name: Philipp Max
    Philipp Max - Age: 28, Matches Played: 14
    Philipp Max - Age: 28, Matches Played: 10
Duplicate name: Andrew Gravillon
    Andrew Gravillon - Age: 24, Matches Played: 13
    Andrew Gravillon - Age: 24, Matches Played: 7
Duplicate name: Kristijan Bistrovic
    Kristijan Bistrovic - Age: 24, Matches Played: 13
    Kristijan Bistrovic - Age: 24, Matches Played: 11
Duplicate name: Koray Gunter
    Koray Gunter - Age: 27, Matches Played: 13
    Koray Gunter - Age: 27, Matches Played: 10
Duplicate name: Goncalo Guedes
    Goncalo Guedes - Age: 25, Matches Played: 13
    Goncalo Guedes - Age: 25, Matches Played: 12
Duplicate name: Giorgos Kyriakopoulos
    Giorgos Kyriakopoulos - Age: 26, Matches Played: 12
    Giorgos Kyriakopoulos - Age: 26, Matches Played: 12
Duplicate name: Manuel Neuer
    Manuel Neuer - Age: 36, Matches Played: 12
    Manuel Neuer - Age: 36, Matches Played: 12
Duplicate name: Jere Uronen
    Jere Uronen - Age: 28, Matches Played: 11
    Jere Uronen - Age: 28, Matches Played: 6
Duplicate name: Mads Bech Sorensen
    Mads Bech Sorensen - Age: 23, Matches Played: 11
    Mads Bech Sorensen - Age: 23, Matches Played: 4
Duplicate name: Kamaldeen Sulemana
    Kamaldeen Sulemana - Age: 20, Matches Played: 18
    Kamaldeen Sulemana - Age: 20, Matches Played: 14
Duplicate name: Danny Ings
    Danny Ings - Age: 30, Matches Played: 18
    Danny Ings - Age: 30, Matches Played: 17
Duplicate name: Terem Moffi
    Terem Moffi - Age: 23, Matches Played: 18
    Terem Moffi - Age: 23, Matches Played: 16
Duplicate name: Valery
    Valery - Age: 22, Matches Played: 30
    Valery - Age: 22, Matches Played: 25
Duplicate name: Mats Hummels
    Mats Hummels - Age: 33, Matches Played: 30
    Mats Hummels - Age: 33, Matches Played: 30
Duplicate name: Anderson
    Anderson - Age: 24, Matches Played: 30
    Anderson - Age: 24, Matches Played: 6
Duplicate name: Mohamed Camara
    Mohamed Camara - Age: 22, Matches Played: 29
    Mohamed Camara - Age: 25, Matches Played: 15
Duplicate name: Dayot Upamecano
    Dayot Upamecano - Age: 23, Matches Played: 29
    Dayot Upamecano - Age: 23, Matches Played: 29
Duplicate name: Niklas Sule
    Niklas Sule - Age: 26, Matches Played: 29
    Niklas Sule - Age: 26, Matches Played: 29
Duplicate name: Nico Schlotterbeck
    Nico Schlotterbeck - Age: 22, Matches Played: 28
    Nico Schlotterbeck - Age: 22, Matches Played: 28
Duplicate name: Ignatius Ganago
    Ignatius Ganago - Age: 23, Matches Played: 28
    Ignatius Ganago - Age: 23, Matches Played: 4
Duplicate name: Marlon
    Marlon - Age: 26, Matches Played: 28
    Marlon - Age: 24, Matches Played: 10
Duplicate name: Armand Lauriente
    Armand Lauriente - Age: 23, Matches Played: 28
    Armand Lauriente - Age: 23, Matches Played: 3
Duplicate name: Gregor Kobel
    Gregor Kobel - Age: 24, Matches Played: 27
    Gregor Kobel - Age: 24, Matches Played: 27
Duplicate name: Leon Goretzka
    Leon Goretzka - Age: 27, Matches Played: 27
    Leon Goretzka - Age: 27, Matches Played: 27
Duplicate name: Thomas Muller
    Thomas Muller - Age: 32, Matches Played: 27
    Thomas Muller - Age: 32, Matches Played: 27
Duplicate name: Kingsley Ehizibue
    Kingsley Ehizibue - Age: 27, Matches Played: 27
    Kingsley Ehizibue - Age: 27, Matches Played: 1
Duplicate name: Emre Can
    Emre Can - Age: 28, Matches Played: 27
    Emre Can - Age: 28, Matches Played: 27
Duplicate name: Neto
    Neto - Age: 30, Matches Played: 27
    Neto - Age: 33, Matches Played: 27
Duplicate name: Raphael Guerreiro
    Raphael Guerreiro - Age: 28, Matches Played: 27
    Raphael Guerreiro - Age: 28, Matches Played: 27
Duplicate name: Arkadiusz Milik
    Arkadiusz Milik - Age: 28, Matches Played: 27
    Arkadiusz Milik - Age: 28, Matches Played: 2
Duplicate name: Nicolas Gonzalez
    Nicolas Gonzalez - Age: 20, Matches Played: 26
    Nicolas Gonzalez - Age: 24, Matches Played: 24
Duplicate name: Youssoufa Moukoko
    Youssoufa Moukoko - Age: 17, Matches Played: 26
    Youssoufa Moukoko - Age: 17, Matches Played: 26
Duplicate name: Benjamin Pavard
    Benjamin Pavard - Age: 26, Matches Played: 30
    Benjamin Pavard - Age: 26, Matches Played: 30
Duplicate name: Wout Faes
    Wout Faes - Age: 24, Matches Played: 31
    Wout Faes - Age: 24, Matches Played: 3
Duplicate name: Salih Ozcan
    Salih Ozcan - Age: 24, Matches Played: 26
    Salih Ozcan - Age: 24, Matches Played: 26
Duplicate name: Jude Bellingham
    Jude Bellingham - Age: 19, Matches Played: 31
    Jude Bellingham - Age: 19, Matches Played: 31
Duplicate name: Fernando
    Fernando - Age: 32, Matches Played: 37
    Fernando - Age: 35, Matches Played: 22
Duplicate name: Rodri
    Rodri - Age: 26, Matches Played: 36
    Rodri - Age: 22, Matches Played: 30
Duplicate name: Ederson
    Ederson - Age: 23, Matches Played: 35
    Ederson - Age: 28, Matches Played: 35
Duplicate name: Alexander Sorloth
    Alexander Sorloth - Age: 26, Matches Played: 34
    Alexander Sorloth - Age: 26, Matches Played: 1
Duplicate name: Pepe
    Pepe - Age: 25, Matches Played: 34
    Pepe - Age: 39, Matches Played: 24
Duplicate name: Serge Gnabry
    Serge Gnabry - Age: 27, Matches Played: 34
    Serge Gnabry - Age: 27, Matches Played: 34
Duplicate name: Matheus Nunes
    Matheus Nunes - Age: 23, Matches Played: 34
    Matheus Nunes - Age: 23, Matches Played: 2
Duplicate name: Ribeiro Almeida Domingos Andre
    Ribeiro Almeida Domingos Andre - Age: 22, Matches Played: 34
    Ribeiro Almeida Domingos Andre - Age: 22, Matches Played: 3
Duplicate name: Costinha
    Costinha - Age: 22, Matches Played: 33
    Costinha - Age: 29, Matches Played: 13
Duplicate name: Joshua Kimmich
    Joshua Kimmich - Age: 27, Matches Played: 33
    Joshua Kimmich - Age: 27, Matches Played: 33
Duplicate name: Jamal Musiala
    Jamal Musiala - Age: 19, Matches Played: 33
    Jamal Musiala - Age: 19, Matches Played: 33
Duplicate name: Gaetan Laborde
    Gaetan Laborde - Age: 28, Matches Played: 33
    Gaetan Laborde - Age: 28, Matches Played: 4
Duplicate name: Amine Gouiri
    Amine Gouiri - Age: 22, Matches Played: 33
    Amine Gouiri - Age: 22, Matches Played: 3
Duplicate name: Marquinhos
    Marquinhos - Age: 28, Matches Played: 33
    Marquinhos - Age: 19, Matches Played: 1
Duplicate name: Antony
    Antony - Age: 20, Matches Played: 33
    Antony - Age: 20, Matches Played: 25
Duplicate name: Julian Brandt
    Julian Brandt - Age: 26, Matches Played: 32
    Julian Brandt - Age: 26, Matches Played: 32
Duplicate name: Leroy Sane
    Leroy Sane - Age: 26, Matches Played: 32
    Leroy Sane - Age: 26, Matches Played: 32
Duplicate name: Matthijs Ligt
    Matthijs Ligt - Age: 22, Matches Played: 31
    Matthijs Ligt - Age: 22, Matches Played: 31
Duplicate name: Andre Silva
    Andre Silva - Age: 26, Matches Played: 31
    Andre Silva - Age: 25, Matches Played: 23
Duplicate name: Alphonso Davies
    Alphonso Davies - Age: 21, Matches Played: 26
    Alphonso Davies - Age: 21, Matches Played: 26
Duplicate name: Donyell Malen
    Donyell Malen - Age: 23, Matches Played: 26
    Donyell Malen - Age: 23, Matches Played: 26
Duplicate name: Kevin Schade
    Kevin Schade - Age: 20, Matches Played: 18
    Kevin Schade - Age: 20, Matches Played: 8
Duplicate name: Akim Zedadka
    Akim Zedadka - Age: 27, Matches Played: 20
    Akim Zedadka - Age: 27, Matches Played: 8
Duplicate name: Jan Bednarek
    Jan Bednarek - Age: 26, Matches Played: 20
    Jan Bednarek - Age: 26, Matches Played: 3
Duplicate name: Mario Lemina
    Mario Lemina - Age: 28, Matches Played: 19
    Mario Lemina - Age: 28, Matches Played: 14
Duplicate name: Sebastien Haller
    Sebastien Haller - Age: 28, Matches Played: 19
    Sebastien Haller - Age: 28, Matches Played: 19
Duplicate name: Noussair Mazraoui
    Noussair Mazraoui - Age: 24, Matches Played: 19
    Noussair Mazraoui - Age: 24, Matches Played: 19
Duplicate name: Anthony Modeste
    Anthony Modeste - Age: 34, Matches Played: 19
    Anthony Modeste - Age: 34, Matches Played: 19
Duplicate name: Sven Mijnans
    Sven Mijnans - Age: 22, Matches Played: 19
    Sven Mijnans - Age: 22, Matches Played: 15
Duplicate name: Bram Nuytinck
    Bram Nuytinck - Age: 32, Matches Played: 19
    Bram Nuytinck - Age: 32, Matches Played: 6
Duplicate name: Sam Lammers
    Sam Lammers - Age: 25, Matches Played: 19
    Sam Lammers - Age: 25, Matches Played: 14
Duplicate name: Karl Toko Ekambi
    Karl Toko Ekambi - Age: 29, Matches Played: 19
    Karl Toko Ekambi - Age: 29, Matches Played: 17
Duplicate name: Alex Moreno
    Alex Moreno - Age: 29, Matches Played: 19
    Alex Moreno - Age: 29, Matches Played: 15
Duplicate name: Dango Ouattara
    Dango Ouattara - Age: 20, Matches Played: 19
    Dango Ouattara - Age: 20, Matches Played: 18
Duplicate name: Amin Sarr

In [27]:
# Drop duplicates based on 'Player' column, keeping the first occurrence (more matches played)
FB.drop_duplicates(subset='Players', keep='first', inplace=True)

In [29]:
duplicates = diff[diff.duplicated(subset='Players', keep=False)]
print(duplicates)

Empty DataFrame
Columns: [Players, Club, Position, Age, Nationality, Values]
Index: []

In [30]:
duplicates = FB[FB.duplicated(subset='Players', keep=False)]
print(duplicates)

Empty DataFrame
Columns: [Players, Age, Matches Played, Start, Minutes, Goals, Assists, Penalties Made, Yellow Cards, Red Cards, Shots, Shots On Target, Shots On Target %, Goals Per Shot, Goals Per Shot On Target, Average Shot Distance, Shots From Freekicks, Passes Completed, Passes, Pass Completion %, Total Passing Distance, Progressive Passing Distance, Shot-Creating Actions, Shot-Creating Actions/90, SCA Pass Live, SCA Pass Dead, SCA Take-ons, SCA Shots, SCA Fouls, SCA Defense, Goal-Creating Actions, Goal-Creating Actions/90, Goal Pass Live, Goal Pass Dead, Goal Take-ons, Goal Shots, Goal Fouls, Goal Defense, Tackles, Tackles Won, Challenges, Successful Challenge %, Blocks, Interceptions, Tackles + Interceptions, Clearances, Errors]
Index: []

[0 rows x 47 columns]

In [31]:
diff.drop('Age', axis = 1, inplace = True)

# Merging Data

In [39]:
merged_df = pd.merge(FB, diff, on=['Players'], how='left')

In [40]:
merged_df

,Players,Age,Matches Played,Start,Minutes,Goals,Assists,Penalties Made,Yellow Cards,Red Cards,...,Successful Challenge %,Blocks,Interceptions,Tackles + Interceptions,Clearances,Errors,Club,Position,Nationality,Values
0,Eberechi Eze,24,38,30,"2,636",10.0,4.0,1.0,3.0,0.0,...,47.4,22.0,13,55.0,10.0,0.0,Crystal Palace,midfield,England,18000000.0
1,Alex Remiro,27,38,38,"3,420",0.0,0.0,0.0,1.0,0.0,...,33.3,0.0,0,1.0,17.0,3.0,Real Sociedad,Goalkeeper,Spain,3000000.0
2,Antoine Griezmann,31,38,31,"2,859",15.0,16.0,0.0,2.0,0.0,...,30.3,34.0,24,73.0,31.0,0.0,Atlético de Madrid,Attack,France,-10000000.0
3,David Raya,26,38,38,"3,420",0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,1,1.0,10.0,2.0,Brentford FC,Goalkeeper,Spain,8000000.0
4,Lautaro Martinez,24,38,27,"2,576",21.0,6.0,1.0,3.0,0.0,...,30.4,31.0,13,38.0,16.0,1.0,Inter Milan,Attack,Argentina,10000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3109,Maximo Perrone,19,1,0,19,0.0,0.0,0.0,0.0,0.0,...,NaN,1.0,0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3110,Hugo Sotelo,18,1,0,17,0.0,0.0,0.0,0.0,0.0,...,NaN,0.0,0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3111,Conor Coventry,22,1,0,1,0.0,0.0,0.0,0.0,0.0,...,NaN,0.0,0,0.0,0.0,0.0,West Ham United,midfield,Ireland,1300000.0
3112,Scott Carson,36,0,0,NaN,NaN,NaN,NaN,NaN,NaN,...,46.6,339.0,223,694.0,402.0,8.0,Manchester City,Goalkeeper,England,-100000.0
3113,Marius Adamonis,25,0,0,NaN,NaN,NaN,NaN,NaN,NaN,...,44.3,437.0,310,892.0,606.0,8.0,SS Lazio,Goalkeeper,Lithuania,0.0

In [36]:
merged_df.dropna(subset=merged_df.columns[-4:], inplace=True)
merged_df = merged_df.sort_values('Values', ascending=False)
merged_df = merged_df.reset_index()
merged_df.fillna(0, inplace=True)

In [38]:
merged_df.sort_values(by='Values', ascending=False, inplace = True)
merged_df

,index,Players,Age,Matches Played,Start,Minutes,Goals,Assists,Penalties Made,Yellow Cards,...,Successful Challenge %,Blocks,Interceptions,Tackles + Interceptions,Clearances,Errors,Club,Position,Nationality,Values
0,626,Randal Kolo Muani,23,32,31,"2,631",15.0,11.0,2.0,6.0,...,11.1,19.0,3,17.0,13.0,0.0,Eintracht Frankfurt,Attack,France,64000000.0
2,40,Bukayo Saka,20,38,37,"3,181",14.0,11.0,2.0,6.0,...,45.5,38.0,14,77.0,19.0,0.0,Arsenal FC,Attack,England,55000000.0
1,684,Victor Osimhen,23,32,30,"2,566",26.0,4.0,2.0,4.0,...,0.0,6.0,6,16.0,29.0,0.0,SSC Napoli,Attack,Nigeria,55000000.0
3,407,Vinicius Junior,22,33,32,"2,823",10.0,9.0,0.0,10.0,...,35.9,24.0,6,36.0,1.0,0.0,Real Madrid,Attack,Brazil,50000000.0
4,405,Alejandro Balde,18,33,30,"2,471",1.0,6.0,0.0,4.0,...,58.5,25.0,12,54.0,17.0,1.0,FC Barcelona,Defender,Spain,46000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1724,2689,Arnaut Danjuma,25,10,6,479,2.0,0.0,1.0,0.0,...,50.0,0.0,0,3.0,1.0,1.0,Villarreal CF,Attack,Netherlands,-25000000.0
1725,1365,Carlos Soler,25,26,14,"1,187",3.0,2.0,0.0,0.0,...,52.6,12.0,4,24.0,6.0,0.0,Paris Saint-Germain,midfield,Spain,-25000000.0
1726,1346,Jadon Sancho,22,26,21,"1,686",6.0,3.0,0.0,0.0,...,28.6,25.0,7,23.0,6.0,0.0,Manchester United,Attack,England,-30000000.0
1727,1543,Romelu Lukaku,29,25,19,"1,660",10.0,6.0,2.0,1.0,...,40.0,3.0,0,3.0,16.0,0.0,Chelsea FC,Attack,Belgium,-30000000.0
1728,1456,Sadio Mane,30,25,18,"1,425",7.0,5.0,1.0,2.0,...,11.1,15.0,0,11.0,4.0,0.0,Bayern Munich,Attack,Senegal,-45000000.0

In [41]:
merged_df.to_csv('dataset.csv', index=False)